import { Recycle, Sprout, Store, Utensils } from "lucide-react";
import type {
  FoodItem,
  ImpactStat,
  OrderDraft,
  PromoCode,
  UrgentItem,
  Vendor,
} from "../types";

const inHours = (hours: number) =>
  new Date(Date.now() + hours * 3600 * 1000).toISOString();

const inMinutes = (minutes: number) =>
  new Date(Date.now() + minutes * 60 * 1000).toISOString();

export const LOCATIONS = [
  "SMP Taruna Bhakti",
  "Kota Bogor",
  "Kota Depok",
  "Jakarta Selatan",
  "Tangerang Selatan",
];

export const foodItems: FoodItem[] = [
  {
    id: "geprek-sambal-bawang",
    name: "Geprek Sambal Bawang",
    vendorName: "Warung Nusantara",
    image: "/makanan1.jpeg",
    category: "Makanan Berat",
    rating: 4.8,
    distanceKm: 0.8,
    availableFrom: "17:00",
    availableTo: "20:00",
    stockLabel: "5 porsi tersisa",
    originalPrice: 35000,
    discountedPrice: 17500,
    discountPercent: 50,
    expiresAt: inHours(3),
  },
  {
    id: "nasi-goreng-gila",
    name: "Nasi Goreng Gila",
    vendorName: "Warkop Pak Iman",
    image: "/makanan2.jpeg",
    category: "Makanan Berat",
    rating: 4.9,
    distanceKm: 0.4,
    availableFrom: "07:00",
    availableTo: "12:00",
    stockLabel: "4 paket tersisa",
    originalPrice: 30000,
    discountedPrice: 15000,
    discountPercent: 50,
  },
  {
    id: "soto-mie-bogor",
    name: "Soto Mie Bogor",
    vendorName: "Warung Nusantara",
    image: "/makanan3.jpeg",
    category: "Makanan Berat",
    rating: 4.7,
    distanceKm: 1.5,
    availableFrom: "11:00",
    availableTo: "14:00",
    stockLabel: "6 porsi tersisa",
    originalPrice: 28000,
    discountedPrice: 16800,
    discountPercent: 40,
    expiresAt: inHours(2),
  },
  {
    id: "sate-ayam-10-pcs",
    name: "Sate Ayam 10 Pcs",
    vendorName: "Warung Nusantara",
    image: "/makanan4.jpeg",
    category: "Makanan Berat",
    rating: 4.6,
    distanceKm: 1.2,
    availableFrom: "08:00",
    availableTo: "13:00",
    stockLabel: "8 box tersisa",
    originalPrice: 25000,
    discountedPrice: 12500,
    discountPercent: 50,
  },
  {
    id: "salad-segar-kebun",
    name: "Salad Segar Kebun",
    vendorName: "Dapur Ibu Tini",
    image: "/makanan5.jpeg",
    category: "Buah & Sayur",
    rating: 4.5,
    distanceKm: 2.0,
    availableFrom: "09:00",
    availableTo: "15:00",
    stockLabel: "6 mangkuk tersisa",
    originalPrice: 24000,
    discountedPrice: 14400,
    discountPercent: 40,
    expiresAt: inHours(5),
  },
  {
    id: "pancong-lumer-coklat-keju",
    name: "Pancong Lumer Coklat Keju",
    vendorName: "Dapur Ibu Tini",
    image: "/makanan6.jpeg",
    category: "Jajanan",
    rating: 4.7,
    distanceKm: 1.1,
    availableFrom: "12:00",
    availableTo: "17:00",
    stockLabel: "3 porsi tersisa",
    originalPrice: 22000,
    discountedPrice: 11000,
    discountPercent: 50,
  },
  {
    id: "martabak-coklat-kacang",
    name: "Martabak Coklat Kacang",
    vendorName: "Dapur Ibu Tini",
    image: "/makanan7.jpg",
    category: "Jajanan",
    rating: 4.8,
    distanceKm: 2.3,
    availableFrom: "18:00",
    availableTo: "21:00",
    stockLabel: "5 porsi tersisa",
    originalPrice: 45000,
    discountedPrice: 27000,
    discountPercent: 40,
  },
  {
    id: "bakso-komplit",
    name: "Bakso Komplit",
    vendorName: "Warkop Pak Iman",
    image: "/makanan8.webp",
    category: "Makanan Berat",
    rating: 4.9,
    distanceKm: 0.6,
    availableFrom: "06:30",
    availableTo: "11:00",
    stockLabel: "2 porsi tersisa",
    originalPrice: 20000,
    discountedPrice: 10000,
    discountPercent: 50,
    expiresAt: inHours(4),
  },
  {
    id: "ketoprak-telor",
    name: "Ketoprak Telor",
    vendorName: "Dapur Ibu Tini",
    image: "/makanan9.webp",
    category: "Makanan Berat",
    rating: 4.6,
    distanceKm: 0.9,
    availableFrom: "13:00",
    availableTo: "16:00",
    stockLabel: "12 porsi tersisa",
    originalPrice: 18000,
    discountedPrice: 9000,
    discountPercent: 50,
  },
  {
    id: "mie-ayam",
    name: "Mie Ayam",
    vendorName: "Warkop Pak Iman",
    image: "/makanan10.webp",
    category: "Makanan Berat",
    rating: 4.7,
    distanceKm: 2.5,
    availableFrom: "17:30",
    availableTo: "20:30",
    stockLabel: "4 porsi tersisa",
    originalPrice: 42000,
    discountedPrice: 25200,
    discountPercent: 40,
  },
  {
    id: "nasi-katsu",
    name: "Nasi Katsu",
    vendorName: "Dapur Ibu Tini",
    image: "/makanan11.jpg",
    category: "Japanese",
    rating: 4.9,
    distanceKm: 1.8,
    availableFrom: "11:30",
    availableTo: "20:00",
    stockLabel: "3 set tersisa",
    originalPrice: 35000,
    discountedPrice: 18000,
    discountPercent: 49,
    expiresAt: inHours(2),
  },
  {
    id: "paket-burger",
    name: "Paket Burger Hemat",
    vendorName: "Dapur Ibu Tini",
    image: "/makanan12.jpg",
    category: "Makanan Cepat Saji",
    rating: 4.8,
    distanceKm: 0.5,
    availableFrom: "08:00",
    availableTo: "16:00",
    stockLabel: "5 pcs tersisa",
    originalPrice: 50000,
    discountedPrice: 35000,
    discountPercent: 18,
  },
  {
    id: "gado-gado",
    name: "Gado Gado + Lontong",
    vendorName: "Warung Nusantara",
    image: "/makanan13.jpg",
    category: "Makanan Berat",
    rating: 4.7,
    distanceKm: 1.0,
    availableFrom: "10:00",
    availableTo: "22:00",
    stockLabel: "4 paket tersisa",
    originalPrice: 50000,
    discountedPrice: 30000,
    discountPercent: 40,
    expiresAt: inHours(3),
  },
  {
    id: "/makanan14.jpg",
    name: "Roti Kopi",
    vendorName: "Dapur Ibu Tini",
    image: "/makanan14.jpg",
    category: "Roti & Kue",
    rating: 4.9,
    distanceKm: 1.4,
    availableFrom: "12:00",
    availableTo: "19:00",
    stockLabel: "2 slice tersisa",
    originalPrice: 38000,
    discountedPrice: 19000,
    discountPercent: 50,
  },
  {
    id: "iced-matcha-latte",
    name: "Iced Matcha Latte",
    vendorName: "Warkop Pak Iman",
    image: "/makanan15.jpg",
    category: "Minuman",
    rating: 4.8,
    distanceKm: 0.7,
    availableFrom: "09:00",
    availableTo: "21:00",
    stockLabel: "10 cup tersisa",
    originalPrice: 25000,
    discountedPrice: 15000,
    discountPercent: 40,
  },
];

export const urgentItems: UrgentItem[] = [
  {
    id: "urgent-geprek-sambal-bawang",
    name: "Geprek Sambal Bawang",
    vendorName: "Warung Nusantara",
    image: "/makanan1.jpeg",
    category: "Makanan Berat",
    rating: 4.8,
    distanceKm: 0.8,
    availableFrom: "17:00",
    availableTo: "20:00",
    stockLabel: "2 porsi tersisa",
    originalPrice: 38000,
    discountedPrice: 19000,
    discountPercent: 50,
    expiresAt: inHours(0.75),
    slot: "15-18",
  },
  {
    id: "urgent-nasi-goreng-gila",
    name: "Nasi Goreng Gila",
    vendorName: "Warkop Pak Iman",
    image: "/makanan2.jpeg",
    category: "Makanan Berat",
    rating: 4.9,
    distanceKm: 0.4,
    availableFrom: "07:00",
    availableTo: "12:00",
    stockLabel: "4 porsi tersisa",
    originalPrice: 30000,
    discountedPrice: 15000,
    discountPercent: 50,
    expiresAt: inHours(1.25),
    slot: "09-12",
  },
  {
    id: "urgent-ketoprak-telor",
    name: "Ketoprak Telor",
    vendorName: "Dapur Ibu Tini",
    image: "/makanan9.webp",
    category: "Makanan Berat",
    rating: 4.6,
    distanceKm: 0.9,
    availableFrom: "13:00",
    availableTo: "16:00",
    stockLabel: "12 porsi tersisa",
    originalPrice: 18000,
    discountedPrice: 9000,
    discountPercent: 50,
    expiresAt: inHours(2),
    slot: "12-15",
  },
  {
    id: "urgent-martabak-coklat-kacang",
    name: "Martabak Coklat Kacang",
    vendorName: "Dapur Ibu Tini",
    image: "/makanan7.jpg",
    category: "Jajanan",
    rating: 4.8,
    distanceKm: 2.3,
    availableFrom: "18:00",
    availableTo: "21:00",
    stockLabel: "3 porsi tersisa",
    originalPrice: 45000,
    discountedPrice: 27000,
    discountPercent: 40,
    expiresAt: inHours(3),
    slot: "18-21",
  },
  {
    id: "urgent-10-pcs-sate-ayam",
    name: "10 Pcs Sate Ayam",
    vendorName: "Warung Nusantara",
    image: "/makanan4.jpeg",
    category: "Makanan Berat",
    rating: 4.6,
    distanceKm: 1.2,
    availableFrom: "08:00",
    availableTo: "13:00",
    stockLabel: "5 box tersisa",
    originalPrice: 40000,
    discountedPrice: 25000,
    discountPercent: 37,
    expiresAt: inHours(4),
    slot: "09-12",
  },
  {
    id: "urgent-rendang-bumbu-spesial",
    name: "Rendang Bumbu Spesial",
    vendorName: "Warung Nusantara",
    image: "/makanan5.jpeg",
    category: "Makanan Berat",
    rating: 4.5,
    distanceKm: 2.0,
    availableFrom: "09:00",
    availableTo: "15:00",
    stockLabel: "4 porsi tersisa",
    originalPrice: 24000,
    discountedPrice: 14400,
    discountPercent: 40,
    expiresAt: inHours(5),
    slot: "12-15",
  },
  {
    id: "urgent-bakso-komplit-nikmat",
    name: "Bakso Komplit Nikmat",
    vendorName: "Warkop Pak Iman",
    image: "/makanan8.webp",
    category: "Makanan Berat",
    rating: 4.9,
    distanceKm: 0.6,
    availableFrom: "06:30",
    availableTo: "11:00",
    stockLabel: "3 paket tersisa",
    originalPrice: 21000,
    discountedPrice: 18000,
    discountPercent: 20,
    expiresAt: inHours(2.25),
    slot: "09-12",
  },
  {
    id: "urgent-soto-mie-bogor",
    name: "Soto Mie Bogor",
    vendorName: "Warung Nusantara",
    image: "/makanan3.jpeg",
    category: "Makanan Berat",
    rating: 4.7,
    distanceKm: 0.8,
    availableFrom: "06:00",
    availableTo: "10:30",
    stockLabel: "4 porsi tersisa",
    originalPrice: 25000,
    discountedPrice: 15000,
    discountPercent: 40,
    expiresAt: inHours(1.5),
    slot: "09-12",
  },
  {
    id: "urgent-pancong-lumer-coklat-keju",
    name: "Pancong Lumer Coklat Keju",
    vendorName: "Dapur Ibu Tini",
    image: "/makanan6.jpeg",
    category: "Jajanan",
    rating: 4.7,
    distanceKm: 1.1,
    availableFrom: "11:00",
    availableTo: "14:00",
    stockLabel: "5 porsi tersisa",
    originalPrice: 28000,
    discountedPrice: 15000,
    discountPercent: 46,
    expiresAt: inHours(2.5),
    slot: "12-15",
  },
  {
    id: "urgent-mie-ayam",
    name: "Mie Ayam",
    vendorName: "Warkop Pak Iman",
    image: "/makanan10.webp",
    category: "Makanan Berat",
    rating: 4.7,
    distanceKm: 2.5,
    availableFrom: "17:30",
    availableTo: "20:30",
    stockLabel: "4 porsi tersisa",
    originalPrice: 22000,
    discountedPrice: 12000,
    discountPercent: 45,
    expiresAt: inHours(1),
    slot: "15-18",
  },
  {
    id: "urgent-10-pcs-sate-ayam-2",
    name: "10 Pcs Sate Ayam",
    vendorName: "Warung Nusantara",
    image: "/makanan4.jpeg",
    category: "Makanan Berat",
    rating: 4.6,
    distanceKm: 1.2,
    availableFrom: "15:00",
    availableTo: "18:00",
    stockLabel: "6 pcs tersisa",
    originalPrice: 40000,
    discountedPrice: 25000,
    discountPercent: 37,
    expiresAt: inHours(2),
    slot: "15-18",
  },
  {
    id: "urgent-geprek-sambal-bawang-malam",
    name: "Geprek Sambal Bawang",
    vendorName: "Warung Nusantara",
    image: "/makanan1.jpeg",
    category: "Makanan Berat",
    rating: 4.8,
    distanceKm: 0.8,
    availableFrom: "18:00",
    availableTo: "21:00",
    stockLabel: "3 porsi tersisa",
    originalPrice: 38000,
    discountedPrice: 19000,
    discountPercent: 50,
    expiresAt: inHours(1.75),
    slot: "18-21",
  },
  {
    id: "urgent-ketoprak-telor-malam",
    name: "Ketoprak Telor",
    vendorName: "Dapur Ibu Tini",
    image: "/makanan9.webp",
    category: "Makanan Berat",
    rating: 4.6,
    distanceKm: 0.9,
    availableFrom: "18:00",
    availableTo: "21:00",
    stockLabel: "10 porsi tersisa",
    originalPrice: 25000,
    discountedPrice: 16000,
    discountPercent: 36,
    expiresAt: inHours(2.75),
    slot: "18-21",
  },
];

export const vendors: Vendor[] = [
  {
    id: "warung-nusantara",
    name: "Warung Nusantara",
    image:
      "https://images.pexels.com/photos/37193132/pexels-photo-37193132.jpeg?auto=compress&cs=tinysrgb&w=800",
    isRescuePartner: true,
    rating: 4.8,
    distanceKm: 0.8,
    category: "Makanan Berat",
    itemCount: 4,
    address: "Jl. Pajajaran No. 18, Bogor",
    openHours: "09.00â€“21.00",
    description:
      "Warung rumahan dengan masakan nusantara otentik. Dari nasi goreng sampai rendang, semua dimasak fresh setiap hari.",
  },
  {
    id: "dapur-ibu-tini",
    name: "Dapur Ibu Tini",
    image:
      "https://images.pexels.com/photos/30294334/pexels-photo-30294334.jpeg?auto=compress&cs=tinysrgb&w=800",
    isRescuePartner: false,
    rating: 4.7,
    distanceKm: 1.1,
    category: "Makanan Berat",
    itemCount: 4,
    address: "Jl. Raya Tajur No. 12, Bogor",
    openHours: "10.00â€“20.00",
    description:
      "Dapur rumahan spesialis kudapan pasar buatan sendiri, dari martabak dan pancong hangat sampai ketoprak dan salad buah segar.",
  },
  {
    id: "warkop-pak-iman",
    name: "Warkop Pak Iman",
    image:
      "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=800",
    isRescuePartner: true,
    rating: 4.9,
    distanceKm: 0.6,
    category: "Makanan & Minuman",
    itemCount: 3,
    address: "Jl. Baranangsiang No. 9, Bogor",
    openHours: "06.30â€“22.00",
    description:
      "Warkop favorit anak Bogor untuk sarapan dan nongkrong. Bakso hangat, roti bakar, dan kopi susu gula aren jadi andalan.",
  },
];

export const impactStats: ImpactStat[] = [
  {
    id: "saved-meals",
    icon: Utensils,
    value: 12540,
    label: "Makanan berhasil diselamatkan",
  },
  {
    id: "waste-shifted",
    icon: Recycle,
    value: 3280,
    suffix: " kg",
    label: "Potensi food waste yang dialihkan",
  },
  {
    id: "buyers",
    icon: Sprout,
    value: 1840,
    label: "Pembeli telah ikut berkontribusi",
  },
  {
    id: "umkm-joined",
    icon: Store,
    value: 426,
    label: "UMKM bergabung",
  },
];

export const formatRupiah = (value: number) =>
  `Rp${value.toLocaleString("id-ID")}`;

export const orderDraft: OrderDraft = {
  productId: "nasi-ayam-surplus",
  productSlug: "paket-nasi-ayam-surplus",
  vendorName: "Dapur Bu Tini",
  vendorSlug: "dapur-ibu-tini",
  productName: "Paket Nasi Ayam Surplus",
  image:
    "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800",
  originalPrice: 30000,
  discountedPrice: 18000,
  stockRemaining: 7,
  distanceKm: 1.1,
  pickupTime: { from: "18:30", to: "20:00" },
  pickupLocation: "Jl. Kenanga No. 12, Bogor Utara",
  reservedUntil: inMinutes(35),
  co2ePerUnitKg: 0.45,
};

export const promoCodes: PromoCode[] = [
  { code: "REBITES26", percentOff: 5, isValid: true },
];
