import {
  Recycle,
  Sprout,
  Store,
  Utensils,
} from 'lucide-react';
import type { FoodItem, ImpactStat, UrgentItem, Vendor } from './types';

const inHours = (hours: number) =>
  new Date(Date.now() + hours * 3600 * 1000).toISOString();

export const LOCATIONS = [
  'SMP Taruna Bhakti',
  'Kota Bogor',
  'Kota Depok',
  'Jakarta Selatan',
  'Tangerang Selatan',
];

export const foodItems: FoodItem[] = [
  {
    id: 'geprek-sambal-bawang',
    name: 'Geprek Sambal Bawang',
    vendorName: 'Warung Nusantara',
    image: '/makanan1.jpeg',
    category: 'Makanan Berat',
    rating: 4.8,
    distanceKm: 0.8,
    availableFrom: '17:00',
    availableTo: '20:00',
    stockLabel: '5 porsi tersisa',
    originalPrice: 35000,
    discountedPrice: 17500,
    discountPercent: 50,
    expiresAt: inHours(3),
  },
  {
    id: 'nasi-goreng-gila',
    name: 'Nasi Goreng Gila',
    vendorName: 'Nasi Goreng Mas Jono',
    image: '/makanan2.jpeg',
    category: 'Roti & Kue',
    rating: 4.9,
    distanceKm: 0.4,
    availableFrom: '07:00',
    availableTo: '12:00',
    stockLabel: '4 paket tersisa',
    originalPrice: 30000,
    discountedPrice: 15000,
    discountPercent: 50,
  },
  {
    id: 'soto-mie-bogor',
    name: 'Soto Mie Bogor',
    vendorName: 'Warung Nusantara',
    image: '/makanan3.jpeg',
    category: 'Makanan Berat',
    rating: 4.7,
    distanceKm: 1.5,
    availableFrom: '11:00',
    availableTo: '14:00',
    stockLabel: '6 porsi tersisa',
    originalPrice: 28000,
    discountedPrice: 16800,
    discountPercent: 40,
    expiresAt: inHours(2),
  },
  {
    id: 'sate-ayam-10-pcs',
    name: 'Sate Ayam 10 Pcs',
    vendorName: 'Warung Nusantara',
    image: '/makanan4.jpeg',
    category: 'Roti & Kue',
    rating: 4.6,
    distanceKm: 1.2,
    availableFrom: '08:00',
    availableTo: '13:00',
    stockLabel: '8 box tersisa',
    originalPrice: 25000,
    discountedPrice: 12500,
    discountPercent: 50,
  },
  {
    id: 'salad-segar-kebun',
    name: 'Salad Segar Kebun',
    vendorName: 'Salad Stop',
    image: '/makanan5.jpeg',
    category: 'Buah & Sayur',
    rating: 4.5,
    distanceKm: 2.0,
    availableFrom: '09:00',
    availableTo: '15:00',
    stockLabel: '6 mangkuk tersisa',
    originalPrice: 24000,
    discountedPrice: 14400,
    discountPercent: 40,
    expiresAt: inHours(5),
  },
  {
    id: 'pancong-lumer-coklat-keju',
    name: 'Pancong Lumer Coklat Keju',
    vendorName: 'Dapur Ibu Tini',
    image: '/makanan6.jpeg',
    category: 'Makanan Berat',
    rating: 4.7,
    distanceKm: 1.1,
    availableFrom: '12:00',
    availableTo: '17:00',
    stockLabel: '3 mangkuk tersisa',
    originalPrice: 22000,
    discountedPrice: 11000,
    discountPercent: 50,
  },
  {
    id: 'martabak-coklat-kacang',
    name: 'Martabak Coklat Kacang',
    vendorName: 'Martabak Go 99',
    image: '/makanan7.jpg',
    category: 'Jajanan',
    rating: 4.8,
    distanceKm: 2.3,
    availableFrom: '18:00',
    availableTo: '21:00',
    stockLabel: '5 porsi tersisa',
    originalPrice: 45000,
    discountedPrice: 27000,
    discountPercent: 40,
  },
  {
    id: 'bakso-komplit',
    name: 'Bakso Komplit',
    vendorName: 'Bakso Si Gendut',
    image: '/makanan8.webp',
    category: 'Roti & Kue',
    rating: 4.9,
    distanceKm: 0.6,
    availableFrom: '06:30',
    availableTo: '11:00',
    stockLabel: '2 paket tersisa',
    originalPrice: 20000,
    discountedPrice: 10000,
    discountPercent: 50,
    expiresAt: inHours(4),
  },
  {
    id: 'ketoprak-telor',
    name: 'Ketoprak Telor',
    vendorName: 'Ketoprak Sedap Siang',
    image: '/makanan9.webp',
    category: 'Makanan Berat',
    rating: 4.6,
    distanceKm: 0.9,
    availableFrom: '13:00',
    availableTo: '16:00',
    stockLabel: '12 porsi tersisa',
    originalPrice: 18000,
    discountedPrice: 9000,
    discountPercent: 50,
  },
  {
    id: 'mie-ayam',
    name: 'Mie Ayam',
    vendorName: 'Bakso Si Gendut',
    image: '/makanan10.webp',
    category: 'Makanan Berat',
    rating: 4.7,
    distanceKm: 2.5,
    availableFrom: '17:30',
    availableTo: '20:30',
    stockLabel: '4 porsi tersisa',
    originalPrice: 42000,
    discountedPrice: 25200,
    discountPercent: 40,
  },
];

export const urgentItems: UrgentItem[] = [
  {
    id: 'urgent-geprek-sambal-bawang',
    name: 'Geprek Sambal Bawang',
    vendorName: 'Warung Nusantara',
    image: '/makanan1.jpeg',
    category: 'Makanan Berat',
    rating: 4.8,
    distanceKm: 0.8,
    availableFrom: '17:00',
    availableTo: '20:00',
    stockLabel: '2 porsi tersisa',
    originalPrice: 38000,
    discountedPrice: 19000,
    discountPercent: 50,
    expiresAt: inHours(0.75),
    slot: '15-18',
  },
  {
    id: 'urgent-nasi-goreng-gila',
    name: 'Nasi Goreng Gila',
    vendorName: 'Nasi Goreng Mas Jono',
    image: '/makanan2.jpeg',
    category: 'Makanan Berat',
    rating: 4.9,
    distanceKm: 0.4,
    availableFrom: '07:00',
    availableTo: '12:00',
    stockLabel: '4 porsi tersisa',
    originalPrice: 30000,
    discountedPrice: 15000,
    discountPercent: 50,
    expiresAt: inHours(1.25),
    slot: '09-12',
  },
  {
    id: 'urgent-ketoprak-telor',
    name: 'Ketoprak Telor',
    vendorName: 'Ketoprak Sedap Siang',
    image: '/makanan9.webp',
    category: 'Makanan Berat',
    rating: 4.6,
    distanceKm: 0.9,
    availableFrom: '13:00',
    availableTo: '16:00',
    stockLabel: '12 porsi tersisa',
    originalPrice: 18000,
    discountedPrice: 9000,
    discountPercent: 50,
    expiresAt: inHours(2),
    slot: '12-15',
  },
  {
    id: 'urgent-martabak-coklat-kacang',
    name: 'Martabak Coklat Kacang',
    vendorName: 'Martabak Go 99',
    image: '/makanan7.jpg',
    category: 'Jajanan',
    rating: 4.8,
    distanceKm: 2.3,
    availableFrom: '18:00',
    availableTo: '21:00',
    stockLabel: '3 porsi tersisa',
    originalPrice: 45000,
    discountedPrice: 27000,
    discountPercent: 40,
    expiresAt: inHours(3),
    slot: '18-21',
  },
  {
    id: 'urgent-10-pcs-sate-ayam',
    name: '10 Pcs Sate Ayam',
    vendorName: 'Sate Pak Tigiset',
    image: '/makanan4.jpeg',
    category: 'Makanan Berat',
    rating: 4.6,
    distanceKm: 1.2,
    availableFrom: '08:00',
    availableTo: '13:00',
    stockLabel: '5 box tersisa',
    originalPrice: 40000,
    discountedPrice: 25000,
    discountPercent: 37,
    expiresAt: inHours(4),
    slot: '09-12',
  },
  {
    id: 'urgent-rendang-bumbu-spesial',
    name: 'Rendang Bumbu Spesial',
    vendorName: 'Padang Karindang',
    image: '/makanan5.jpeg',
    category: 'Makanan Berat',
    rating: 4.5,
    distanceKm: 2.0,
    availableFrom: '09:00',
    availableTo: '15:00',
    stockLabel: '4 porsi tersisa',
    originalPrice: 24000,
    discountedPrice: 14400,
    discountPercent: 40,
    expiresAt: inHours(5),
    slot: '12-15',
  },
  {
    id: 'urgent-bakso-komplit-nikmat',
    name: 'Bakso Komplit Nikmat',
    vendorName: 'Bakso si Gendut',
    image: '/makanan8.webp',
    category: 'Makanan Berat',
    rating: 4.9,
    distanceKm: 0.6,
    availableFrom: '06:30',
    availableTo: '11:00',
    stockLabel: '3 paket tersisa',
    originalPrice: 21000,
    discountedPrice: 18000,
    discountPercent: 20,
    expiresAt: inHours(2.25),
    slot: '09-12',
  },
  {
    id: 'urgent-soto-mie-bogor',
    name: 'Soto Mie Bogor',
    vendorName: 'Warung Nusantara',
    image: '/makanan3.jpeg',
    category: 'Makanan Berat',
    rating: 4.7,
    distanceKm: 0.8,
    availableFrom: '06:00',
    availableTo: '10:30',
    stockLabel: '4 porsi tersisa',
    originalPrice: 25000,
    discountedPrice: 15000,
    discountPercent: 40,
    expiresAt: inHours(1.5),
    slot: '09-12',
  },
  {
    id: 'urgent-pancong-lumer-coklat-keju',
    name: 'Pancong Lumer Coklat Keju',
    vendorName: 'Dapur Ibu Tini',
    image: '/makanan6.jpeg',
    category: 'Jajanan',
    rating: 4.7,
    distanceKm: 1.1,
    availableFrom: '11:00',
    availableTo: '14:00',
    stockLabel: '5 porsi tersisa',
    originalPrice: 28000,
    discountedPrice: 15000,
    discountPercent: 46,
    expiresAt: inHours(2.5),
    slot: '12-15',
  },
  {
    id: 'urgent-mie-ayam',
    name: 'Mie Ayam',
    vendorName: 'Mie Ayam Bahari',
    image: '/makanan10.webp',
    category: 'Makanan Berat',
    rating: 4.7,
    distanceKm: 2.5,
    availableFrom: '17:30',
    availableTo: '20:30',
    stockLabel: '4 porsi tersisa',
    originalPrice: 22000,
    discountedPrice: 12000,
    discountPercent: 45,
    expiresAt: inHours(1),
    slot: '15-18',
  },
  {
    id: 'urgent-10-pcs-sate-ayam-2',
    name: '10 Pcs Sate Ayam',
    vendorName: 'Sate Pak Tigiset',
    image: '/makanan4.jpeg',
    category: 'Makanan Berat',
    rating: 4.6,
    distanceKm: 1.2,
    availableFrom: '15:00',
    availableTo: '18:00',
    stockLabel: '6 pcs tersisa',
    originalPrice: 40000,
    discountedPrice: 25000,
    discountPercent: 37,
    expiresAt: inHours(2),
    slot: '15-18',
  },
  {
    id: 'urgent-geprek-sambal-bawang-malam',
    name: 'Geprek Sambal Bawang',
    vendorName: 'Warung Nusantara',
    image: '/makanan1.jpeg',
    category: 'Makanan Berat',
    rating: 4.8,
    distanceKm: 0.8,
    availableFrom: '18:00',
    availableTo: '21:00',
    stockLabel: '3 porsi tersisa',
    originalPrice: 38000,
    discountedPrice: 19000,
    discountPercent: 50,
    expiresAt: inHours(1.75),
    slot: '18-21',
  },
  {
    id: 'urgent-ketoprak-telor-malam',
    name: 'Ketoprak Telor',
    vendorName: 'Ketoprak Sedap Siang',
    image: '/makanan9.webp',
    category: 'Makanan Berat',
    rating: 4.6,
    distanceKm: 0.9,
    availableFrom: '18:00',
    availableTo: '21:00',
    stockLabel: '10 porsi tersisa',
    originalPrice: 25000,
    discountedPrice: 16000,
    discountPercent: 36,
    expiresAt: inHours(2.75),
    slot: '18-21',
  },
];

export const vendors: Vendor[] = [
  {
    id: 'warung-nusantara',
    name: 'Warung Nusantara',
    image:
      'https://images.pexels.com/photos/37193132/pexels-photo-37193132.jpeg?auto=compress&cs=tinysrgb&w=800',
    isRescuePartner: true,
    rating: 4.8,
    distanceKm: 0.8,
    category: 'Makanan Berat',
    itemCount: 3,
    address: 'Jl. Pajajaran No. 18, Bogor',
    openHours: '09.00–21.00',
  },
  {
    id: 'nasi-goreng-mas-jono',
    name: 'Nasi Goreng Mas Jono',
    image:
      'https://images.pexels.com/photos/19066564/pexels-photo-19066564.jpeg?auto=compress&cs=tinysrgb&w=800',
    isRescuePartner: true,
    rating: 4.9,
    distanceKm: 0.4,
    category: 'Makanan Berat',
    itemCount: 2,
    address: 'Jl. Suryakencana No. 7, Bogor',
    openHours: '06.00–14.00',
  },
  {
    id: 'dapur-ibu-tini',
    name: 'Dapur Ibu Tini',
    image:
      'https://images.pexels.com/photos/30294334/pexels-photo-30294334.jpeg?auto=compress&cs=tinysrgb&w=800',
    isRescuePartner: false,
    rating: 4.7,
    distanceKm: 1.1,
    category: 'Makanan Berat',
    itemCount: 2,
    address: 'Jl. Raya Tajur No. 12, Bogor',
    openHours: '10.00–20.00',
  },
  {
    id: 'sate-ayam-pak-tigiset',
    name: 'Sate Ayam Pak Tigiset',
    image:
      'https://images.pexels.com/photos/31118377/pexels-photo-31118377.jpeg?auto=compress&cs=tinysrgb&w=800',
    isRescuePartner: false,
    rating: 4.6,
    distanceKm: 1.2,
    category: 'Makanan Berat',
    itemCount: 1,
    address: 'Jl. Paledang No. 5, Bogor',
    openHours: '16.00–22.00',
  },
  {
    id: 'padang-karindang',
    name: 'Padang Karindang',
    image:
      'https://images.pexels.com/photos/35258440/pexels-photo-35258440.jpeg?auto=compress&cs=tinysrgb&w=800',
    isRescuePartner: true,
    rating: 4.5,
    distanceKm: 2.0,
    category: 'Makanan Berat',
    itemCount: 1,
    address: 'Jl. Veteran No. 23, Bogor',
    openHours: '10.00–21.00',
  },
  {
    id: 'martabak-go-99',
    name: 'Martabak Go 99',
    image:
      'https://images.pexels.com/photos/37129828/pexels-photo-37129828.jpeg?auto=compress&cs=tinysrgb&w=800',
    isRescuePartner: true,
    rating: 4.7,
    distanceKm: 2.3,
    category: 'Jajanan',
    itemCount: 2,
    address: 'Jl. Jend. Sudirman No. 3, Bogor',
    openHours: '17.00–23.00',
  },
  {
    id: 'bakso-si-gendut',
    name: 'Bakso si Gendut',
    image:
      'https://images.pexels.com/photos/35398717/pexels-photo-35398717.jpeg?auto=compress&cs=tinysrgb&w=800',
    isRescuePartner: false,
    rating: 4.9,
    distanceKm: 0.6,
    category: 'Makanan Berat',
    itemCount: 1,
    address: 'Jl. Baranangsiang No. 9, Bogor',
    openHours: '09.00–19.00',
  },
  {
    id: 'ketoprak-sedap-siang',
    name: 'Ketoprak Sedap Siang',
    image:
      'https://images.pexels.com/photos/29831531/pexels-photo-29831531.jpeg?auto=compress&cs=tinysrgb&w=800',
    isRescuePartner: true,
    rating: 4.6,
    distanceKm: 0.9,
    category: 'Makanan Berat',
    itemCount: 1,
    address: 'Jl. Raya Cibinong No. 45, Bogor',
    openHours: '11.00–21.00',
  },
];

export const impactStats: ImpactStat[] = [
  {
    id: 'saved-meals',
    icon: Utensils,
    value: 12540,
    label: 'Makanan berhasil diselamatkan',
  },
  {
    id: 'waste-shifted',
    icon: Recycle,
    value: 3280,
    suffix: ' kg',
    label: 'Potensi food waste yang dialihkan',
  },
  {
    id: 'buyers',
    icon: Sprout,
    value: 1840,
    label: 'Pembeli telah ikut berkontribusi',
  },
  {
    id: 'umkm-joined',
    icon: Store,
    value: 426,
    label: 'UMKM bergabung',
  },
];

export const formatRupiah = (value: number) =>
  `Rp${value.toLocaleString('id-ID')}`;