import {
  Recycle,
  Sprout,
  Store,
  Utensils,
} from 'lucide-react';
import type { FoodItem, ImpactStat, UrgentItem, Vendor } from './types';

const inHours = (hours: number) =>
  new Date(Date.now() + hours * 3600 * 1000).toISOString();

export const LOCATIONS = [
  'SMP Taruna Bhakti',
  'Kota Bogor',
  'Kota Depok',
  'Jakarta Selatan',
  'Tangerang Selatan',
];

export const foodItems: FoodItem[] = [
  {
    id: 'nasi-ayam-komplit',
    name: 'Nasi Ayam Komplit',
    vendorName: 'Warung Nusantara',
    image:
      'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'restoran',
    rating: 4.8,
    distanceKm: 0.8,
    availableFrom: '17:00',
    availableTo: '20:00',
    stockLabel: '5 porsi tersisa',
    originalPrice: 35000,
    discountedPrice: 17500,
    discountPercent: 50,
    expiresAt: inHours(3),
  },
  {
    id: 'paket-roti-campur',
    name: 'Paket Roti Campur',
    vendorName: 'Roti Subuh',
    image: '/foods/rotisourdough.jpg',
    category: 'bakery',
    rating: 4.9,
    distanceKm: 0.4,
    availableFrom: '07:00',
    availableTo: '12:00',
    stockLabel: '4 paket tersisa',
    originalPrice: 30000,
    discountedPrice: 15000,
    discountPercent: 50,
  },
  {
    id: 'rice-bowl-ayam',
    name: 'Rice Bowl Ayam',
    vendorName: 'Dapur Ibu Tini',
    image:
      'https://images.pexels.com/photos/19572488/pexels-photo-19572488.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'restoran',
    rating: 4.7,
    distanceKm: 1.5,
    availableFrom: '11:00',
    availableTo: '14:00',
    stockLabel: '6 porsi tersisa',
    originalPrice: 28000,
    discountedPrice: 16800,
    discountPercent: 40,
    expiresAt: inHours(2),
  },
  {
    id: 'donat-mix',
    name: 'Donat Mix',
    vendorName: 'Kue Mbok Ndari',
    image: '/foods/boxdonat.jpg',
    category: 'bakery',
    rating: 4.6,
    distanceKm: 1.2,
    availableFrom: '08:00',
    availableTo: '13:00',
    stockLabel: '8 box tersisa',
    originalPrice: 25000,
    discountedPrice: 12500,
    discountPercent: 50,
  },
  {
    id: 'salad-segar-kebun',
    name: 'Salad Segar Kebun',
    vendorName: 'Salad Stop',
    image: '/foods/saladkebun.jpg',
    category: 'umkm',
    rating: 4.5,
    distanceKm: 2.0,
    availableFrom: '09:00',
    availableTo: '15:00',
    stockLabel: '6 mangkuk tersisa',
    originalPrice: 24000,
    discountedPrice: 14400,
    discountPercent: 40,
    expiresAt: inHours(5),
  },
  {
    id: 'sup-krim-labu',
    name: 'Sup Krim Labu Hangat',
    vendorName: 'Dapur Ibu Tini',
    image: '/foods/supkrimlabu.jpg',
    category: 'umkm',
    rating: 4.7,
    distanceKm: 1.1,
    availableFrom: '12:00',
    availableTo: '17:00',
    stockLabel: '3 mangkuk tersisa',
    originalPrice: 22000,
    discountedPrice: 11000,
    discountPercent: 50,
  },
  {
    id: 'pasta-carbonara',
    name: 'Pasta Carbonara Surplus',
    vendorName: 'Segar Bahari',
    image: '/foods/pastacarbonara.jpg',
    category: 'restoran',
    rating: 4.8,
    distanceKm: 2.3,
    availableFrom: '18:00',
    availableTo: '21:00',
    stockLabel: '5 porsi tersisa',
    originalPrice: 45000,
    discountedPrice: 27000,
    discountPercent: 40,
  },
  {
    id: 'sandwich-croissant',
    name: 'Sandwich Croissant Pagi',
    vendorName: 'Croissant & Co',
    image: '/foods/sandwichcroissant.jpg',
    category: 'bakery',
    rating: 4.9,
    distanceKm: 0.6,
    availableFrom: '06:30',
    availableTo: '11:00',
    stockLabel: '2 paket tersisa',
    originalPrice: 20000,
    discountedPrice: 10000,
    discountPercent: 50,
    expiresAt: inHours(4),
  },
  {
    id: 'kopi-susu-barista',
    name: 'Kopi Susu Sisa Barista',
    vendorName: 'Kopi Pagi',
    image: '/foods/kopisusu.jpg',
    category: 'minuman',
    rating: 4.6,
    distanceKm: 0.9,
    availableFrom: '13:00',
    availableTo: '16:00',
    stockLabel: '12 cangkir tersisa',
    originalPrice: 18000,
    discountedPrice: 9000,
    discountPercent: 50,
  },
  {
    id: 'ikan-sayur-surplus',
    name: 'Ikan & Sayur Surplus Hari Ini',
    vendorName: 'Segar Bahari',
    image: '/foods/ikansayur.jpg',
    category: 'restoran',
    rating: 4.7,
    distanceKm: 2.5,
    availableFrom: '17:30',
    availableTo: '20:30',
    stockLabel: '4 porsi tersisa',
    originalPrice: 42000,
    discountedPrice: 25200,
    discountPercent: 40,
  },
];

export const urgentItems: UrgentItem[] = [
  {
    id: 'urgent-ayam-bakar',
    name: 'Ayam Bakar Komplit',
    vendorName: 'Warung Nusantara',
    image:
      'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'restoran',
    rating: 4.8,
    distanceKm: 0.8,
    availableFrom: '17:00',
    availableTo: '20:00',
    stockLabel: '2 porsi tersisa',
    originalPrice: 38000,
    discountedPrice: 19000,
    discountPercent: 50,
    expiresAt: inHours(0.75),
  },
  {
    id: 'urgent-sourdough',
    name: 'Paket Roti Sourdough Sisa Panggang',
    vendorName: 'Roti Subuh',
    image: '/foods/rotisourdough.jpg',
    category: 'bakery',
    rating: 4.9,
    distanceKm: 0.4,
    availableFrom: '07:00',
    availableTo: '12:00',
    stockLabel: '4 paket tersisa',
    originalPrice: 30000,
    discountedPrice: 15000,
    discountPercent: 50,
    expiresAt: inHours(1.25),
  },
  {
    id: 'urgent-kopi-susu',
    name: 'Kopi Susu Sisa Barista',
    vendorName: 'Kopi Pagi',
    image: '/foods/kopisusu.jpg',
    category: 'minuman',
    rating: 4.6,
    distanceKm: 0.9,
    availableFrom: '13:00',
    availableTo: '16:00',
    stockLabel: '12 cangkir tersisa',
    originalPrice: 18000,
    discountedPrice: 9000,
    discountPercent: 50,
    expiresAt: inHours(2),
  },
  {
    id: 'urgent-carbonara',
    name: 'Pasta Carbonara Surplus',
    vendorName: 'Segar Bahari',
    image: '/foods/pastacarbonara.jpg',
    category: 'restoran',
    rating: 4.8,
    distanceKm: 2.3,
    availableFrom: '18:00',
    availableTo: '21:00',
    stockLabel: '3 porsi tersisa',
    originalPrice: 45000,
    discountedPrice: 27000,
    discountPercent: 40,
    expiresAt: inHours(3),
  },
  {
    id: 'urgent-donat',
    name: 'Box Donat Mini Rasa Campur',
    vendorName: 'Kue Mbok Ndari',
    image: '/foods/boxdonat.jpg',
    category: 'bakery',
    rating: 4.6,
    distanceKm: 1.2,
    availableFrom: '08:00',
    availableTo: '13:00',
    stockLabel: '5 box tersisa',
    originalPrice: 25000,
    discountedPrice: 12500,
    discountPercent: 50,
    expiresAt: inHours(4),
  },
  {
    id: 'urgent-salad',
    name: 'Salad Segar Kebun',
    vendorName: 'Salad Stop',
    image: '/foods/saladkebun.jpg',
    category: 'umkm',
    rating: 4.5,
    distanceKm: 2.0,
    availableFrom: '09:00',
    availableTo: '15:00',
    stockLabel: '4 mangkuk tersisa',
    originalPrice: 24000,
    discountedPrice: 14400,
    discountPercent: 40,
    expiresAt: inHours(5),
  },
];

export const vendors: Vendor[] = [
  {
    id: 'warung-nusantara',
    name: 'Warung Nusantara',
    image: '/foods/ikansayur.jpg',
    logo: 'WN',
    isRescuePartner: true,
    rating: 4.8,
    distanceKm: 0.8,
    category: 'Masakan Rumah',
    itemCount: 3,
  },
  {
    id: 'roti-subuh',
    name: 'Roti Subuh',
    image: '/foods/rotisourdough.jpg',
    logo: 'RS',
    isRescuePartner: true,
    rating: 4.9,
    distanceKm: 0.4,
    category: 'Roti & Pastry',
    itemCount: 2,
  },
  {
    id: 'dapur-ibu-tini',
    name: 'Dapur Ibu Tini',
    image: '/foods/supkrimlabu.jpg',
    logo: 'DI',
    isRescuePartner: false,
    rating: 4.7,
    distanceKm: 1.1,
    category: 'Masakan Rumah',
    itemCount: 2,
  },
  {
    id: 'kue-mbok-ndari',
    name: 'Kue Mbok Ndari',
    image: '/foods/boxdonat.jpg',
    logo: 'KM',
    isRescuePartner: false,
    rating: 4.6,
    distanceKm: 1.2,
    category: 'Kue & Jajanan',
    itemCount: 1,
  },
  {
    id: 'salad-stop',
    name: 'Salad Stop',
    image: '/foods/saladkebun.jpg',
    logo: 'SS',
    isRescuePartner: true,
    rating: 4.5,
    distanceKm: 2.0,
    category: 'Salad & Sehat',
    itemCount: 1,
  },
  {
    id: 'segar-bahari',
    name: 'Segar Bahari',
    image: '/foods/pastacarbonara.jpg',
    logo: 'SB',
    isRescuePartner: true,
    rating: 4.7,
    distanceKm: 2.3,
    category: 'Pasta & Western',
    itemCount: 2,
  },
  {
    id: 'croissant-co',
    name: 'Croissant & Co',
    image: '/foods/sandwichcroissant.jpg',
    logo: 'CC',
    isRescuePartner: false,
    rating: 4.9,
    distanceKm: 0.6,
    category: 'Bakery & Sandwich',
    itemCount: 1,
  },
  {
    id: 'kopi-pagi',
    name: 'Kopi Pagi',
    image: '/foods/kopisusu.jpg',
    logo: 'KP',
    isRescuePartner: true,
    rating: 4.6,
    distanceKm: 0.9,
    category: 'Kopi & Minuman',
    itemCount: 1,
  },
];

export const impactStats: ImpactStat[] = [
  {
    id: 'saved-meals',
    icon: Utensils,
    value: 12540,
    label: 'Makanan berhasil diselamatkan',
  },
  {
    id: 'waste-shifted',
    icon: Recycle,
    value: 3280,
    suffix: ' kg',
    label: 'Potensi food waste yang dialihkan',
  },
  {
    id: 'buyers',
    icon: Sprout,
    value: 1840,
    label: 'Pembeli telah ikut berkontribusi',
  },
  {
    id: 'umkm-joined',
    icon: Store,
    value: 426,
    label: 'UMKM bergabung',
  },
];

export const formatRupiah = (value: number) =>
  `Rp${value.toLocaleString('id-ID')}`;
